import type { Metadata } from "next";
import "../style/global.css";
import { JetBrains_Mono } from "next/font/google";
import SectionContainer from "./sections/sectionContainer";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} antialiased bg-black`}>
        {children}
      </body>
    </html>
  );
}
